services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"


  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: >
      etcd -advertise-client-urls=http://0.0.0.0:2379
           -listen-client-urls=http://0.0.0.0:2379
           -listen-peer-urls=http://0.0.0.0:2380
           -initial-advertise-peer-urls=http://0.0.0.0:2380
           -initial-cluster=default=http://0.0.0.0:2380
           -data-dir=/etcd
    ports:
      - "2379:2379"
    restart: always

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: milvus-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./volumes/minio:/data
    command: server /data
    ports:
      - "9000:9000"
    restart: always

  milvus:
    image: milvusdb/milvus:v2.3.4
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    depends_on:
      - etcd
      - minio
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"   # Milvus SDK Port
      - "9091:9091"     # Milvus Metrics
    restart: always

  attu:
    image: zilliz/attu:latest
    container_name: attu
    depends_on:
      - milvus
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "8000:3000"   # Attu UI bereikbaar op http://localhost:8000
    restart: always

networks:
  default:
    name: milvus-network

volumes:
  open-webui:
